2021-04-28 01:41:25 INFO     All arguments used for this run
    Namespace(arch='custom', batch_size=128, data='/home/dataset/ILSVRC/Data/CLS-LOC', dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', epochs=15, evaluate=False, gpu=None, img=256, jitter_train=[], jitter_val=[], keep_logs=True, lr=0.001, momentum=0.9, multiprocessing_distributed=False, normalize=True, pretrained=False, print_freq=1000, rank=-1, resume='', seed=None, start_epoch=0, weight_decay=0.0001, workers=4, world_size=-1)
    
2021-04-28 01:41:25 INFO     => using custom model
2021-04-28 01:41:26 INFO     Model Config: *** KERNEL SIZE OF 5 ***
    VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 128, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(128, 256, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(256, 256, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (11): Conv2d(256, 512, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 512, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (14): ReLU(inplace=True)
    (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (16): Conv2d(512, 512, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (17): ReLU(inplace=True)
    (18): Conv2d(512, 512, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
    (19): ReLU(inplace=True)
    (20): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(7, 7))
  (classifier): Sequential(
    (0): Linear(in_features=25088, out_features=4096, bias=True)
    (1): ReLU(inplace=True)
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=4096, out_features=4096, bias=True)
    (4): ReLU(inplace=True)
    (5): Dropout(p=0.5, inplace=False)
    (6): Linear(in_features=4096, out_features=1000, bias=True)
  )
)
    
2021-04-28 01:41:47 INFO     Epoch: [0][    0/10010]	Time 13.451 (13.451)	Data  1.966 ( 1.966)	Loss 6.9082e+00 (6.9082e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
2021-04-28 01:53:54 INFO     Epoch: [0][ 1000/10010]	Time  0.726 ( 0.739)	Data  0.000 ( 0.010)	Loss 6.9073e+00 (6.9078e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.56)
2021-04-28 02:05:59 INFO     Epoch: [0][ 2000/10010]	Time  0.724 ( 0.732)	Data  0.000 ( 0.005)	Loss 6.9077e+00 (6.9078e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.55)
2021-04-28 02:18:04 INFO     Epoch: [0][ 3000/10010]	Time  0.722 ( 0.730)	Data  0.000 ( 0.004)	Loss 6.9076e+00 (6.9078e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.54)
2021-04-28 02:30:09 INFO     Epoch: [0][ 4000/10010]	Time  0.725 ( 0.729)	Data  0.000 ( 0.003)	Loss 6.9093e+00 (6.9078e+00)	Acc@1   0.00 (  0.10)	Acc@5   1.56 (  0.53)
2021-04-28 02:42:15 INFO     Epoch: [0][ 5000/10010]	Time  0.725 ( 0.728)	Data  0.001 ( 0.003)	Loss 6.9072e+00 (6.9077e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.52)
2021-04-28 02:54:20 INFO     Epoch: [0][ 6000/10010]	Time  0.727 ( 0.727)	Data  0.000 ( 0.002)	Loss 6.9069e+00 (6.9077e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.52)
2021-04-28 03:06:25 INFO     Epoch: [0][ 7000/10010]	Time  0.725 ( 0.727)	Data  0.000 ( 0.002)	Loss 6.9070e+00 (6.9077e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.78 (  0.52)
2021-04-28 03:18:30 INFO     Epoch: [0][ 8000/10010]	Time  0.727 ( 0.727)	Data  0.000 ( 0.002)	Loss 6.9079e+00 (6.9077e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.52)
2021-04-28 03:30:35 INFO     Epoch: [0][ 9000/10010]	Time  0.724 ( 0.727)	Data  0.000 ( 0.002)	Loss 6.9081e+00 (6.9077e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.51)
2021-04-28 03:42:41 INFO     Epoch: [0][10000/10010]	Time  0.724 ( 0.727)	Data  0.000 ( 0.002)	Loss 6.9085e+00 (6.9077e+00)	Acc@1   0.78 (  0.10)	Acc@5   1.56 (  0.51)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 03:42:52 INFO     Test: [  0/391]	Time  2.746 ( 2.746)	Loss 6.9080e+00 (6.9080e+00)	Acc@1   0.00 (  0.00)	Acc@5   1.56 (  1.56)
2021-04-28 03:46:29 INFO      * Acc@1 0.100 Acc@5 0.516
2021-04-28 03:46:37 INFO     Epoch: [1][    0/10010]	Time  2.763 ( 2.763)	Data  2.395 ( 2.395)	Loss 6.9076e+00 (6.9076e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
2021-04-28 03:58:42 INFO     Epoch: [1][ 1000/10010]	Time  0.727 ( 0.727)	Data  0.000 ( 0.003)	Loss 6.9083e+00 (6.9075e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.55)
2021-04-28 04:10:48 INFO     Epoch: [1][ 2000/10010]	Time  0.726 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.9065e+00 (6.9074e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.53)
2021-04-28 04:22:52 INFO     Epoch: [1][ 3000/10010]	Time  0.724 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.9079e+00 (6.9074e+00)	Acc@1   0.00 (  0.11)	Acc@5   1.56 (  0.53)
2021-04-28 04:34:57 INFO     Epoch: [1][ 4000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9093e+00 (6.9074e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.53)
2021-04-28 04:47:02 INFO     Epoch: [1][ 5000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9058e+00 (6.9074e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.53)
2021-04-28 04:59:07 INFO     Epoch: [1][ 6000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9093e+00 (6.9074e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.52)
2021-04-28 05:11:12 INFO     Epoch: [1][ 7000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9080e+00 (6.9074e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.52)
2021-04-28 05:23:17 INFO     Epoch: [1][ 8000/10010]	Time  0.727 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9085e+00 (6.9074e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.51)
2021-04-28 05:35:22 INFO     Epoch: [1][ 9000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9068e+00 (6.9073e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.51)
2021-04-28 05:47:27 INFO     Epoch: [1][10000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9065e+00 (6.9073e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.51)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 05:47:36 INFO     Test: [  0/391]	Time  2.464 ( 2.464)	Loss 6.9091e+00 (6.9091e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
2021-04-28 05:51:05 INFO      * Acc@1 0.100 Acc@5 0.486
2021-04-28 05:51:15 INFO     Epoch: [2][    0/10010]	Time  2.365 ( 2.365)	Data  2.123 ( 2.123)	Loss 6.9064e+00 (6.9064e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
2021-04-28 06:03:20 INFO     Epoch: [2][ 1000/10010]	Time  0.725 ( 0.727)	Data  0.000 ( 0.003)	Loss 6.9085e+00 (6.9071e+00)	Acc@1   0.00 (  0.12)	Acc@5   0.00 (  0.54)
2021-04-28 06:15:25 INFO     Epoch: [2][ 2000/10010]	Time  0.722 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.9083e+00 (6.9071e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.52)
2021-04-28 06:27:30 INFO     Epoch: [2][ 3000/10010]	Time  0.723 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.9076e+00 (6.9071e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.52)
2021-04-28 06:39:35 INFO     Epoch: [2][ 4000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9060e+00 (6.9071e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.51)
2021-04-28 06:51:40 INFO     Epoch: [2][ 5000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9075e+00 (6.9071e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.50)
2021-04-28 07:03:45 INFO     Epoch: [2][ 6000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9043e+00 (6.9071e+00)	Acc@1   0.00 (  0.10)	Acc@5   1.56 (  0.50)
2021-04-28 07:15:50 INFO     Epoch: [2][ 7000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9059e+00 (6.9071e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.51)
2021-04-28 07:27:55 INFO     Epoch: [2][ 8000/10010]	Time  0.727 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9074e+00 (6.9071e+00)	Acc@1   0.00 (  0.10)	Acc@5   1.56 (  0.51)
2021-04-28 07:40:00 INFO     Epoch: [2][ 9000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9069e+00 (6.9071e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.52)
2021-04-28 07:52:05 INFO     Epoch: [2][10000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9074e+00 (6.9070e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.78 (  0.52)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 07:52:14 INFO     Test: [  0/391]	Time  2.563 ( 2.563)	Loss 6.9075e+00 (6.9075e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.78 (  0.78)
2021-04-28 07:55:41 INFO      * Acc@1 0.154 Acc@5 0.528
2021-04-28 07:55:57 INFO     Epoch: [3][    0/10010]	Time  2.213 ( 2.213)	Data  1.973 ( 1.973)	Loss 6.9061e+00 (6.9061e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.00 (  0.00)
2021-04-28 08:08:02 INFO     Epoch: [3][ 1000/10010]	Time  0.726 ( 0.726)	Data  0.000 ( 0.003)	Loss 6.9049e+00 (6.9067e+00)	Acc@1   0.00 (  0.09)	Acc@5   0.00 (  0.56)
2021-04-28 08:20:07 INFO     Epoch: [3][ 2000/10010]	Time  0.724 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.9039e+00 (6.9065e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.56)
2021-04-28 08:32:12 INFO     Epoch: [3][ 3000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.9008e+00 (6.9055e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.00 (  0.54)
2021-04-28 08:44:17 INFO     Epoch: [3][ 4000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8797e+00 (6.9031e+00)	Acc@1   0.00 (  0.10)	Acc@5   0.78 (  0.53)
2021-04-28 08:56:22 INFO     Epoch: [3][ 5000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8869e+00 (6.9001e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.55)
2021-04-28 09:08:27 INFO     Epoch: [3][ 6000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8649e+00 (6.8962e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.00 (  0.56)
2021-04-28 09:20:32 INFO     Epoch: [3][ 7000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8518e+00 (6.8920e+00)	Acc@1   0.00 (  0.11)	Acc@5   0.78 (  0.57)
2021-04-28 09:32:37 INFO     Epoch: [3][ 8000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8558e+00 (6.8875e+00)	Acc@1   0.00 (  0.12)	Acc@5   0.78 (  0.60)
2021-04-28 09:44:42 INFO     Epoch: [3][ 9000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.8314e+00 (6.8832e+00)	Acc@1   0.00 (  0.12)	Acc@5   1.56 (  0.62)
2021-04-28 09:56:47 INFO     Epoch: [3][10000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.7684e+00 (6.8785e+00)	Acc@1   0.00 (  0.13)	Acc@5   1.56 (  0.64)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 09:56:55 INFO     Test: [  0/391]	Time  2.451 ( 2.451)	Loss 6.7741e+00 (6.7741e+00)	Acc@1   0.78 (  0.78)	Acc@5   0.78 (  0.78)
2021-04-28 10:00:24 INFO      * Acc@1 0.162 Acc@5 0.824
2021-04-28 10:00:40 INFO     Epoch: [4][    0/10010]	Time  2.386 ( 2.386)	Data  2.137 ( 2.137)	Loss 6.8638e+00 (6.8638e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.78 (  0.78)
2021-04-28 10:12:45 INFO     Epoch: [4][ 1000/10010]	Time  0.721 ( 0.727)	Data  0.000 ( 0.003)	Loss 6.8147e+00 (6.8245e+00)	Acc@1   0.78 (  0.19)	Acc@5   3.91 (  0.85)
2021-04-28 10:24:50 INFO     Epoch: [4][ 2000/10010]	Time  0.724 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.8294e+00 (6.8147e+00)	Acc@1   0.00 (  0.18)	Acc@5   0.78 (  0.88)
2021-04-28 10:36:55 INFO     Epoch: [4][ 3000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.001)	Loss 6.7658e+00 (6.8065e+00)	Acc@1   0.78 (  0.18)	Acc@5   0.78 (  0.88)
2021-04-28 10:49:00 INFO     Epoch: [4][ 4000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.7860e+00 (6.7998e+00)	Acc@1   0.78 (  0.19)	Acc@5   1.56 (  0.90)
2021-04-28 11:01:05 INFO     Epoch: [4][ 5000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.6456e+00 (6.7897e+00)	Acc@1   0.00 (  0.19)	Acc@5   0.00 (  0.92)
2021-04-28 11:13:10 INFO     Epoch: [4][ 6000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.6290e+00 (6.7704e+00)	Acc@1   0.00 (  0.19)	Acc@5   1.56 (  0.94)
2021-04-28 11:25:15 INFO     Epoch: [4][ 7000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.6412e+00 (6.7518e+00)	Acc@1   0.00 (  0.20)	Acc@5   0.00 (  0.96)
2021-04-28 11:37:19 INFO     Epoch: [4][ 8000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.5966e+00 (6.7348e+00)	Acc@1   0.00 (  0.20)	Acc@5   0.78 (  0.98)
2021-04-28 11:49:24 INFO     Epoch: [4][ 9000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.5774e+00 (6.7192e+00)	Acc@1   0.00 (  0.20)	Acc@5   3.12 (  1.01)
2021-04-28 12:01:29 INFO     Epoch: [4][10000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.3883e+00 (6.7036e+00)	Acc@1   1.56 (  0.21)	Acc@5   3.91 (  1.05)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 12:01:38 INFO     Test: [  0/391]	Time  2.352 ( 2.352)	Loss 6.5034e+00 (6.5034e+00)	Acc@1   0.00 (  0.00)	Acc@5   0.78 (  0.78)
2021-04-28 12:05:06 INFO      * Acc@1 0.380 Acc@5 1.692
2021-04-28 12:05:22 INFO     Epoch: [5][    0/10010]	Time  2.133 ( 2.133)	Data  1.901 ( 1.901)	Loss 6.5502e+00 (6.5502e+00)	Acc@1   0.00 (  0.00)	Acc@5   3.12 (  3.12)
2021-04-28 12:17:27 INFO     Epoch: [5][ 1000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.003)	Loss 6.5338e+00 (6.5360e+00)	Acc@1   0.00 (  0.32)	Acc@5   0.00 (  1.44)
2021-04-28 12:29:32 INFO     Epoch: [5][ 2000/10010]	Time  0.723 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.4674e+00 (6.5220e+00)	Acc@1   0.00 (  0.34)	Acc@5   0.78 (  1.53)
2021-04-28 12:41:37 INFO     Epoch: [5][ 3000/10010]	Time  0.728 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.4780e+00 (6.5085e+00)	Acc@1   0.78 (  0.34)	Acc@5   3.12 (  1.60)
2021-04-28 12:53:42 INFO     Epoch: [5][ 4000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.3996e+00 (6.4960e+00)	Acc@1   0.78 (  0.35)	Acc@5   1.56 (  1.63)
2021-04-28 13:05:46 INFO     Epoch: [5][ 5000/10010]	Time  0.722 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.3260e+00 (6.4836e+00)	Acc@1   1.56 (  0.37)	Acc@5   1.56 (  1.68)
2021-04-28 13:17:51 INFO     Epoch: [5][ 6000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.3780e+00 (6.4701e+00)	Acc@1   0.00 (  0.38)	Acc@5   0.78 (  1.74)
2021-04-28 13:29:56 INFO     Epoch: [5][ 7000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.2588e+00 (6.4524e+00)	Acc@1   0.78 (  0.41)	Acc@5   1.56 (  1.86)
2021-04-28 13:42:01 INFO     Epoch: [5][ 8000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.2937e+00 (6.4333e+00)	Acc@1   0.78 (  0.44)	Acc@5   3.91 (  2.00)
2021-04-28 13:54:06 INFO     Epoch: [5][ 9000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.2918e+00 (6.4146e+00)	Acc@1   0.00 (  0.46)	Acc@5   0.78 (  2.12)
2021-04-28 14:06:11 INFO     Epoch: [5][10000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.1756e+00 (6.3953e+00)	Acc@1   0.00 (  0.49)	Acc@5   3.91 (  2.23)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 14:06:20 INFO     Test: [  0/391]	Time  2.470 ( 2.470)	Loss 6.1165e+00 (6.1165e+00)	Acc@1   0.78 (  0.78)	Acc@5   6.25 (  6.25)
2021-04-28 14:09:48 INFO      * Acc@1 1.040 Acc@5 4.706
2021-04-28 14:10:04 INFO     Epoch: [6][    0/10010]	Time  2.423 ( 2.423)	Data  2.191 ( 2.191)	Loss 6.1510e+00 (6.1510e+00)	Acc@1   0.00 (  0.00)	Acc@5   5.47 (  5.47)
2021-04-28 14:22:09 INFO     Epoch: [6][ 1000/10010]	Time  0.724 ( 0.727)	Data  0.000 ( 0.003)	Loss 6.2420e+00 (6.1913e+00)	Acc@1   1.56 (  0.83)	Acc@5   4.69 (  3.56)
2021-04-28 14:34:14 INFO     Epoch: [6][ 2000/10010]	Time  0.722 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.1028e+00 (6.1751e+00)	Acc@1   0.78 (  0.86)	Acc@5   5.47 (  3.70)
2021-04-28 14:46:19 INFO     Epoch: [6][ 3000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.002)	Loss 6.1273e+00 (6.1624e+00)	Acc@1   1.56 (  0.90)	Acc@5   5.47 (  3.83)
2021-04-28 14:58:24 INFO     Epoch: [6][ 4000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.0470e+00 (6.1488e+00)	Acc@1   1.56 (  0.92)	Acc@5   3.91 (  3.95)
2021-04-28 15:10:28 INFO     Epoch: [6][ 5000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.0414e+00 (6.1356e+00)	Acc@1   0.78 (  0.94)	Acc@5   6.25 (  4.04)
2021-04-28 15:22:33 INFO     Epoch: [6][ 6000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.0353e+00 (6.1225e+00)	Acc@1   1.56 (  0.96)	Acc@5  10.94 (  4.17)
2021-04-28 15:34:38 INFO     Epoch: [6][ 7000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.8173e+00 (6.1048e+00)	Acc@1   2.34 (  1.00)	Acc@5   6.25 (  4.33)
2021-04-28 15:46:43 INFO     Epoch: [6][ 8000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.1172e+00 (6.0850e+00)	Acc@1   0.78 (  1.05)	Acc@5   7.03 (  4.51)
2021-04-28 15:58:48 INFO     Epoch: [6][ 9000/10010]	Time  0.721 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.8635e+00 (6.0646e+00)	Acc@1   2.34 (  1.10)	Acc@5   7.81 (  4.73)
2021-04-28 16:10:53 INFO     Epoch: [6][10000/10010]	Time  0.722 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.7817e+00 (6.0438e+00)	Acc@1   3.91 (  1.17)	Acc@5   9.38 (  4.95)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 16:11:02 INFO     Test: [  0/391]	Time  2.370 ( 2.370)	Loss 5.7783e+00 (5.7783e+00)	Acc@1   0.00 (  0.00)	Acc@5   4.69 (  4.69)
2021-04-28 16:14:31 INFO      * Acc@1 2.456 Acc@5 9.388
2021-04-28 16:14:47 INFO     Epoch: [7][    0/10010]	Time  2.216 ( 2.216)	Data  1.974 ( 1.974)	Loss 5.7708e+00 (5.7708e+00)	Acc@1   3.91 (  3.91)	Acc@5  10.94 ( 10.94)
2021-04-28 16:26:52 INFO     Epoch: [7][ 1000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.003)	Loss 5.7513e+00 (5.8190e+00)	Acc@1   0.00 (  1.89)	Acc@5   6.25 (  7.51)
2021-04-28 16:38:57 INFO     Epoch: [7][ 2000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.002)	Loss 5.8184e+00 (5.8050e+00)	Acc@1   0.78 (  1.92)	Acc@5   6.25 (  7.69)
2021-04-28 16:51:02 INFO     Epoch: [7][ 3000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.7049e+00 (5.7857e+00)	Acc@1   2.34 (  2.00)	Acc@5  11.72 (  7.97)
2021-04-28 17:03:07 INFO     Epoch: [7][ 4000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.6797e+00 (5.7679e+00)	Acc@1   2.34 (  2.09)	Acc@5  11.72 (  8.22)
2021-04-28 17:15:12 INFO     Epoch: [7][ 5000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 6.0580e+00 (5.7472e+00)	Acc@1   1.56 (  2.18)	Acc@5   8.59 (  8.49)
2021-04-28 17:27:17 INFO     Epoch: [7][ 6000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.6813e+00 (5.7266e+00)	Acc@1   3.91 (  2.27)	Acc@5  12.50 (  8.80)
2021-04-28 17:39:22 INFO     Epoch: [7][ 7000/10010]	Time  0.720 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.7710e+00 (5.7091e+00)	Acc@1   3.91 (  2.36)	Acc@5   9.38 (  9.06)
2021-04-28 17:51:27 INFO     Epoch: [7][ 8000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.3484e+00 (5.6910e+00)	Acc@1   3.91 (  2.45)	Acc@5  17.19 (  9.34)
2021-04-28 18:03:32 INFO     Epoch: [7][ 9000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.7857e+00 (5.6722e+00)	Acc@1   2.34 (  2.56)	Acc@5   7.81 (  9.64)
2021-04-28 18:15:37 INFO     Epoch: [7][10000/10010]	Time  0.722 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.4065e+00 (5.6541e+00)	Acc@1   2.34 (  2.66)	Acc@5  13.28 (  9.92)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 18:15:45 INFO     Test: [  0/391]	Time  2.448 ( 2.448)	Loss 5.3101e+00 (5.3101e+00)	Acc@1   4.69 (  4.69)	Acc@5  14.84 ( 14.84)
2021-04-28 18:19:13 INFO      * Acc@1 5.000 Acc@5 16.434
2021-04-28 18:19:30 INFO     Epoch: [8][    0/10010]	Time  2.449 ( 2.449)	Data  2.214 ( 2.214)	Loss 5.3429e+00 (5.3429e+00)	Acc@1   4.69 (  4.69)	Acc@5  19.53 ( 19.53)
2021-04-28 18:31:35 INFO     Epoch: [8][ 1000/10010]	Time  0.728 ( 0.727)	Data  0.000 ( 0.003)	Loss 5.4174e+00 (5.4533e+00)	Acc@1   3.91 (  3.78)	Acc@5  17.97 ( 13.16)
2021-04-28 18:43:40 INFO     Epoch: [8][ 2000/10010]	Time  0.726 ( 0.726)	Data  0.000 ( 0.002)	Loss 5.5023e+00 (5.4329e+00)	Acc@1   3.91 (  3.94)	Acc@5  15.62 ( 13.57)
2021-04-28 18:55:45 INFO     Epoch: [8][ 3000/10010]	Time  0.726 ( 0.726)	Data  0.000 ( 0.001)	Loss 5.4467e+00 (5.4123e+00)	Acc@1   3.91 (  4.11)	Acc@5  15.62 ( 13.97)
2021-04-28 19:07:50 INFO     Epoch: [8][ 4000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.1402e+00 (5.3971e+00)	Acc@1   5.47 (  4.25)	Acc@5  14.84 ( 14.26)
2021-04-28 19:19:55 INFO     Epoch: [8][ 5000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.0245e+00 (5.3806e+00)	Acc@1   7.03 (  4.37)	Acc@5  25.78 ( 14.55)
2021-04-28 19:32:00 INFO     Epoch: [8][ 6000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.2259e+00 (5.3636e+00)	Acc@1   4.69 (  4.50)	Acc@5  16.41 ( 14.87)
2021-04-28 19:44:05 INFO     Epoch: [8][ 7000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.1514e+00 (5.3461e+00)	Acc@1   3.12 (  4.64)	Acc@5  14.84 ( 15.19)
2021-04-28 19:56:10 INFO     Epoch: [8][ 8000/10010]	Time  0.722 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.4262e+00 (5.3286e+00)	Acc@1   3.91 (  4.78)	Acc@5  14.06 ( 15.51)
2021-04-28 20:08:15 INFO     Epoch: [8][ 9000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.0018e+00 (5.3120e+00)	Acc@1   7.81 (  4.91)	Acc@5  20.31 ( 15.83)
2021-04-28 20:20:20 INFO     Epoch: [8][10000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.0386e+00 (5.2956e+00)	Acc@1   3.91 (  5.04)	Acc@5  15.62 ( 16.14)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 20:20:28 INFO     Test: [  0/391]	Time  2.440 ( 2.440)	Loss 4.7958e+00 (4.7958e+00)	Acc@1  10.16 ( 10.16)	Acc@5  20.31 ( 20.31)
2021-04-28 20:23:57 INFO      * Acc@1 8.096 Acc@5 23.686
2021-04-28 20:24:13 INFO     Epoch: [9][    0/10010]	Time  2.378 ( 2.378)	Data  2.133 ( 2.133)	Loss 5.2189e+00 (5.2189e+00)	Acc@1   8.59 (  8.59)	Acc@5  21.09 ( 21.09)
2021-04-28 20:36:18 INFO     Epoch: [9][ 1000/10010]	Time  0.724 ( 0.727)	Data  0.000 ( 0.003)	Loss 5.4150e+00 (5.0970e+00)	Acc@1   7.81 (  6.57)	Acc@5  18.75 ( 19.80)
2021-04-28 20:48:23 INFO     Epoch: [9][ 2000/10010]	Time  0.724 ( 0.726)	Data  0.000 ( 0.002)	Loss 4.9854e+00 (5.0801e+00)	Acc@1   8.59 (  6.75)	Acc@5  20.31 ( 20.26)
2021-04-28 21:00:28 INFO     Epoch: [9][ 3000/10010]	Time  0.723 ( 0.726)	Data  0.000 ( 0.001)	Loss 4.9357e+00 (5.0686e+00)	Acc@1   4.69 (  6.89)	Acc@5  21.88 ( 20.48)
2021-04-28 21:12:33 INFO     Epoch: [9][ 4000/10010]	Time  0.723 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.0387e+00 (5.0558e+00)	Acc@1  10.16 (  6.98)	Acc@5  20.31 ( 20.70)
2021-04-28 21:24:38 INFO     Epoch: [9][ 5000/10010]	Time  0.728 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.0757e+00 (5.0414e+00)	Acc@1   7.81 (  7.13)	Acc@5  25.78 ( 20.99)
2021-04-28 21:36:43 INFO     Epoch: [9][ 6000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.7678e+00 (5.0277e+00)	Acc@1   8.59 (  7.24)	Acc@5  25.78 ( 21.26)
2021-04-28 21:48:48 INFO     Epoch: [9][ 7000/10010]	Time  0.722 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.9345e+00 (5.0135e+00)	Acc@1  10.94 (  7.38)	Acc@5  28.91 ( 21.53)
2021-04-28 22:00:53 INFO     Epoch: [9][ 8000/10010]	Time  0.728 ( 0.725)	Data  0.000 ( 0.001)	Loss 5.2549e+00 (4.9983e+00)	Acc@1   7.81 (  7.52)	Acc@5  21.88 ( 21.82)
2021-04-28 22:12:58 INFO     Epoch: [9][ 9000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.7814e+00 (4.9839e+00)	Acc@1  10.94 (  7.66)	Acc@5  28.91 ( 22.10)
2021-04-28 22:25:03 INFO     Epoch: [9][10000/10010]	Time  0.729 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.9505e+00 (4.9695e+00)	Acc@1   4.69 (  7.80)	Acc@5  19.53 ( 22.38)
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
2021-04-28 22:25:11 INFO     Test: [  0/391]	Time  2.274 ( 2.274)	Loss 4.5444e+00 (4.5444e+00)	Acc@1  12.50 ( 12.50)	Acc@5  32.81 ( 32.81)
2021-04-28 22:28:44 INFO      * Acc@1 12.086 Acc@5 31.016
2021-04-28 22:28:59 INFO     Epoch: [10][    0/10010]	Time  2.383 ( 2.383)	Data  2.148 ( 2.148)	Loss 4.6619e+00 (4.6619e+00)	Acc@1  10.16 ( 10.16)	Acc@5  32.03 ( 32.03)
2021-04-28 22:41:04 INFO     Epoch: [10][ 1000/10010]	Time  0.725 ( 0.727)	Data  0.001 ( 0.003)	Loss 4.5900e+00 (4.7991e+00)	Acc@1   7.81 (  9.37)	Acc@5  29.69 ( 25.72)
2021-04-28 22:53:09 INFO     Epoch: [10][ 2000/10010]	Time  0.727 ( 0.726)	Data  0.000 ( 0.002)	Loss 4.7402e+00 (4.7890e+00)	Acc@1  10.16 (  9.52)	Acc@5  26.56 ( 25.92)
2021-04-28 23:05:14 INFO     Epoch: [10][ 3000/10010]	Time  0.725 ( 0.726)	Data  0.000 ( 0.001)	Loss 4.6061e+00 (4.7794e+00)	Acc@1  11.72 (  9.68)	Acc@5  28.91 ( 26.14)
2021-04-28 23:17:19 INFO     Epoch: [10][ 4000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.7430e+00 (4.7668e+00)	Acc@1   8.59 (  9.80)	Acc@5  26.56 ( 26.42)
2021-04-28 23:29:24 INFO     Epoch: [10][ 5000/10010]	Time  0.727 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.7958e+00 (4.7548e+00)	Acc@1  10.94 (  9.94)	Acc@5  25.00 ( 26.68)
2021-04-28 23:41:29 INFO     Epoch: [10][ 6000/10010]	Time  0.727 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.4908e+00 (4.7413e+00)	Acc@1  15.62 ( 10.09)	Acc@5  35.94 ( 26.98)
2021-04-28 23:53:34 INFO     Epoch: [10][ 7000/10010]	Time  0.726 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.6666e+00 (4.7285e+00)	Acc@1  14.06 ( 10.24)	Acc@5  29.69 ( 27.24)
2021-04-29 00:05:39 INFO     Epoch: [10][ 8000/10010]	Time  0.725 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.4621e+00 (4.7154e+00)	Acc@1   8.59 ( 10.38)	Acc@5  31.25 ( 27.48)
2021-04-29 00:17:44 INFO     Epoch: [10][ 9000/10010]	Time  0.724 ( 0.725)	Data  0.000 ( 0.001)	Loss 4.6767e+00 (4.7029e+00)	Acc@1  10.94 ( 10.54)	Acc@5  28.91 ( 27.74)
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 9518) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 536, in <module>
    main()
  File "main.py", line 178, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 352, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 390, in train
    for i, (images, target) in enumerate(train_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 9518) exited unexpectedly
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

